# Generated by Django 3.1 on 2020-08-26 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0002_productstock_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStockMoviment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantidade')),
                ('moviment_type', models.IntegerField(choices=[(0, 'Venda'), (1, 'Consumo Interno'), (2, 'Descarte'), (3, 'Extravio')], default=0, verbose_name='Tipo de movimentação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('product_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.productstock', verbose_name='Produto em estoque')),
            ],
            options={
                'verbose_name': 'Movimentação de produto em estoque',
                'verbose_name_plural': 'Movimentações de produtos em estoque',
                'ordering': ['-created_at'],
            },
        ),
    ]
