# Generated by Django 3.1 on 2020-08-26 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstockmoviment',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade'),
        ),
    ]
